[package]
name = "aoc-2020-08"
version = "0.1.0"
authors = ["cor <cor@pruijs.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-2020-common = { path = "../common/" }
regex = "1.4.2"
