[package]
name = "aoc-2023-10"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-2023-common = { path = "../common/" }
colored = "2.1.0"
