[package]
name = "aoc-2022-12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-2022-common = { path = "../common/" }
nalgebra = "0.31.4"
